name: Terraform Unit Tests

on:
  push:
    branches:
    - 'feature**'
  pull_request:
      branches:
        - main

jobs:
  build:
    name: Run Terraform Unit Tests
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubOIDCRole
      - run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: |
          terraform init -backend=false

      - name: Terraform Format
        run: |
          terraform fmt

      - name: Terraform Validate
        run: |
          terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: latest

      - name: Init TFLint
        run: |
          tflint --init --config=".tflint.hcl"

      - name: Run TFLint
        run: |
          tflint -f compact --config=".tflint.hcl"
